export default {
  feelsLike: 'Feels like',
  wind: 'Wind',
  pressure: 'Pressure',
  humidity: 'Humidity',
  UVIndex: 'UV Index',
  hourlyWeather: 'Hourly weather',
  hourForecast: '24-hour forecast',
  weeklyForecast: 'Weekly weather',
  nextDays: 'Next 7 days',
  sunrise: 'Sunrise',
  sunset: 'Sunset',
  settings: 'Settings',
  yesterday: 'Yesterday',
  today: 'Today',
  tomorrow: 'Tomorrow',
  mmHg: 'mmHg',
  hPa: 'hPa',
  ms: 'm/s',
  kmh: 'km/h',
  km: 'km',
  calm: 'Calm',
  windSpeed: 'Wind speed',
  temperature: 'Temperature',
  ozone: 'Ozone',
  visibility: 'Visibility',
  cloudCover: 'Cloud cover',
  dewPoint: 'Dew Point',
  chanceOf: 'Сhance of',
  windDirection: {
    nne: 'NNE',
    ne: 'NE',
    ene: 'ENE',
    e: 'E',
    ese: 'ESE',
    se: 'SE',
    sse: 'SSE',
    s: 'S',
    ssw: 'SSW',
    sw: 'SW',
    wsw: 'WSW',
    w: 'w',
    wnw: 'WNW',
    nw: 'NW',
    nnw: 'NNW',
    n: 'N',
  },
};
