export default {
  feelsLike: 'Ощущается как',
  wind: 'Ветер',
  pressure: 'Давление',
  humidity: 'Влажность',
  UVIndex: 'UV Индекс',
  hourlyWeather: 'Почасовой прогноз',
  hourForecast: '24-х часовой прогноз',
  weeklyForecast: 'Прогноз на неделю',
  nextDays: 'Следующие 7 дней',
  sunrise: 'Восход',
  sunset: 'Закат',
  settings: 'Настройки',
  yesterday: 'Вчера',
  today: 'Сегодня',
  tomorrow: 'Завтра',
  mmHg: 'мм рт.ст.',
  hPa: 'гПа',
  ms: 'м/с',
  kmh: 'км/ч',
  km: 'км',
  calm: 'Штиль',
  windSpeed: 'Скорость ветра',
  temperature: 'Температура',
  ozone: 'Озон',
  visibility: 'Видимость',
  cloudCover: 'Облачность',
  dewPoint: 'Точка росы',
  chanceOf: 'Вероятность',
  windDirection: {
    nne: 'ССВ',
    ne: 'СВ',
    ene: 'ВСВ',
    e: 'В',
    ese: 'ВЮВ',
    se: 'ЮВ',
    sse: 'ЮВ',
    s: 'Ю',
    ssw: 'ЮЗ',
    sw: 'ЮЗ',
    wsw: 'ЗЮЗ',
    w: 'З',
    wnw: 'ЗСЗ',
    nw: 'СЗ',
    nnw: 'СЗ',
    n: 'С',
  },
};
